import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navbar from './Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main>
        <aside>
          <h2>Categories</h2>

          <ul class="categories">
            <li class="category-item">
              <a href="#">Men</a>
            </li>
            <li class="category-item">
              <a href="#">Women</a>
            </li>

            <li class="category-item">
              <a href="#">Kids</a>
            </li>

            <li class="category-item">
              <a href="#">Accessories</a>
            </li>
            <li class="category-item">
              <a href="#">Brands</a>
            </li>
          </ul>
        </aside>

        <section>
          <article>
            <img src="https://static.zajo.net/content/mediagallery/zajo_dcat/image/product/types/X/9088.png" />
            <p class="price-item">
              <i class="fas fa-dollar-sign">
                9.00
              </i>
            </p>
            <button>Details</button>
          </article>
          <article>
            <img
              src="https://assetscdn1.paytm.com/images/catalog/product/A/AP/APPEYEBOGLER-COSEVE88413F32E363/1601890054864_0..jpg" />
            <p class="price-item">
              <i class="fas fa-dollar-sign">
                10.00
              </i>
            </p>
            <button>Details</button>
          </article>
          <article>
            <img
              src="https://sportland.com/media/catalog/product/cache/e4932a31a34e41e69084883e2b608489/N/B/NB16158_500_1a17.jpg" />
            <p class="price-item">
              <i class="fas fa-dollar-sign">
                18.00
              </i>
            </p>
            <button>Details</button>
          </article>

          <article>
            <img
              src="https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/192790/02/sv01/fnd/EEA/fmt/png/Flyer-Runner-Engineered-Knit-Men's-Running-Shoes" />
            <p class="price-item">
              <i class="fas fa-dollar-sign">
                12.00
              </i>
            </p>
            <button>Details</button>
          </article>
          <article>
            <img
              src="https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/022605/01/fnd/EEA/fmt/png/Suisse-DNA-Football-Cap" />
            <p class="price-item">
              <i class="fas fa-dollar-sign">
                14.00
              </i>
            </p>
            <button>Details</button>
          </article>
          <article>
            <img src="https://i.pinimg.com/originals/7b/25/ee/7b25ee2805c1c94c82150393dd92e775.jpg" />
            <p class="price-item">
              <i class="fas fa-dollar-sign">
                27.00
              </i>
            </p>
            <button>Details</button>
          </article>
        </section>

        <section>
          <div class="pagination">
            <a href="#">&laquo;</a>
            <a href="#">1</a>
            <a href="#">2</a>
            <a href="#">3</a>
            <a href="#">&raquo;</a>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
